#include "stdafx.h"
#include "Translate.h"
#include <sstream>

std::shared_ptr<CTranslate> pTranslate = std::make_shared<CTranslate>( );

CTranslate::CTranslate( )
{
	m_Address = ( DWORD )VirtualAlloc( nullptr, 0x100000, MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE );
	m_SpaceCount = 0;
	//SetTranslations( );
}

void CTranslate::SetTranslations( )
{
	//Login
	Translate( 0x008368F0, "Priston Tale - Returns" );
	Translate( 0x009F2A7C, "http://www.pstale.com.br" );
	Translate( 0x009F2C88, "Penetrando no orifício do Ravel..." );
	Translate( 0x009F2C8C, "Impossível conectar" );
	Translate( 0x009F2C90, "Conta incorreta" );
	Translate( 0x009F2C94, "Senha incorreta" );
	Translate( 0x009F2C98, "Conta bloqueada" );
	Translate( 0x009F2C9C, "Esta conta já está logada" );
	Translate( 0x009F2CA0, "Versão incompatível" );
	Translate( 0x009F2CA4, "O servidor está cheio" );

	//Char Select
	Translate( 0x009F2CF0, "Você tem certeza que deseja deletar esse personagem?" );
	Translate( 0x009F2CF4, "Você deseja continuar esta aventura?" );
	Translate( 0x009F2CF8, "Cada conta só pode ter no máximo 5 personagens" );
	Translate( 0x009F2CFC, "Você tem certeza que deseja este nome para o seu personagem?" );
	Translate( 0x009F2D00, "Digite um nome para o seu personagem" );
	Translate( 0x009F2D04, "Já existe um personagem com este nome. Por favor, escolha outro" );
	Translate( 0x009F2D08, "Escolha um personagem" );
	Translate( 0x009F2D0C, "Escolha uma tribo" );
	Translate( 0x009F2D10, "Escolha uma classe" );
	Translate( 0x009F2D18, "Este personagem faz parte de um Clã e por isso não pode ser deletado" );
	Translate( 0x009F2D50, "Tempskron" );
	Translate( 0x009F2D34, "Morion" );

	//Classes
	Translate( 0x00837EC4, "Mecânico" );
	Translate( 0x00837FA0, "Mestre Mecânico" );
	Translate( 0x0083807C, "Líder Mecânico" );
	Translate( 0x00838158, "Metaleiro" );
	Translate( 0x00837EF0, "Lutador" );
	Translate( 0x00837FCC, "Guerreiro" );
	Translate( 0x008380A8, "Campeão" );
	Translate( 0x00838184, "Guerreiro Imortal" );
	Translate( 0x00837F1C, "Pike" );
	Translate( 0x00837FF8, "Combatente" );
	Translate( 0x008380D4, "Lancer" );
	Translate( 0x008381B0, "Lancelot" );
	Translate( 0x00837F48, "Arqueira" );
	Translate( 0x00838024, "Mestra da Caça" );
	Translate( 0x00838100, "Discípula de Dion" );
	Translate( 0x008381DC, "Sagitária" );
	Translate( 0x00838310, "Cavaleiro" );
	Translate( 0x008383EC, "Paladino" );
	Translate( 0x008384C8, "Cavaleiro Sagrado" );
	Translate( 0x008385A4, "Cavaleiro Santo" );
	Translate( 0x0083833C, "Atalanta" );
	Translate( 0x00838418, "Valquíria" );
	Translate( 0x008384F4, "Brynhild" );
	Translate( 0x008385D0, "Valhala" );
	Translate( 0x00838368, "Sacerdotisa" );
	Translate( 0x00838444, "Santa" );
	Translate( 0x00838520, "Episcopisa" );
	Translate( 0x008385FC, "Celestial" );
	Translate( 0x00838394, "Mago" );
	Translate( 0x00838470, "Feiticeiro" );
	Translate( 0x0083854C, "Feiticeiro Real" );
	Translate( 0x00838628, "Bruxo" );

	//Ajuda e Guia
	Translate( 0x0098E524, "    Ajuda" );
	Translate( 0x0064FFF6, "> Abrir Guia" );
	Translate( 0x00650015, "> Abrir Guia" );
	Translate( 0x0064DCE0, "     Guia" );
	Translate( 0x0064E071, "     Guia" );
	Translate( 0x0064CCE1, "Nível 1" );
	Translate( 0x0064CCF3, "Nível 2" );
	Translate( 0x0064CD07, "Níve" );
	Translate( 0x0064CD15, "l 3" );
	Translate( 0x0064CD1E, "" );
	Translate( 0x0064CD44, "Níve" );
	Translate( 0x0064CD52, "l 4" );
	Translate( 0x0064CD5B, "" );
	Translate( 0x0064CD63, "Nível 5" );
	Translate( 0x0064CD78, "Níve" );
	Translate( 0x0064CD86, "l 6" );
	Translate( 0x0064CD8F, "" );
	Translate( 0x0064CDAC, "Níve" );
	Translate( 0x0064CDBA, "l 7" );
	Translate( 0x0064CDC4, "" );
	Translate( 0x0064CDCD, "Nível 8" );
	Translate( 0x0064CDE1, "Níve" );
	Translate( 0x0064CDEF, "l 9" );
	Translate( 0x0064CDF9, "" );
	Translate( 0x0064CE0C, "Níve" );
	Translate( 0x0064CE1A, "l 10" );
	Translate( 0x0064CE23, "" );
	Translate( 0x0064CE2C, "Níve" );
	Translate( 0x0064CE3A, "l 11" );
	Translate( 0x0064CE43, "" );
	Translate( 0x0064CE68, "Nível 12" );
	Translate( 0x0064CE70, "Nível 15" );
	Translate( 0x0064CE85, "Nível 17" );
	Translate( 0x0064CE99, "Nível 20" );
	Translate( 0x0064CEAE, "Nível 22" );
	Translate( 0x0064CEC0, "Nível 25" );
	Translate( 0x0064CED9, "Nível 30" );
	Translate( 0x0064CEE9, "Níve" );
	Translate( 0x0064CEF7, "l 39" );
	Translate( 0x0064CF00, "" );
	Translate( 0x0064CF1C, "Nível 40" );
	Translate( 0x0064CF2E, "Nível 50" );
	Translate( 0x0064CF42, "Nível 55" );
	Translate( 0x0064CF57, "Nível 60" );
	Translate( 0x0064CF6B, "Nível 65" );
	Translate( 0x0064CF7D, "Nível 70" );
	Translate( 0x0064CF90, "Nível 75" );
	Translate( 0x0064CFA3, "Nível 79" );
	Translate( 0x0064CFB6, "Nível 80" );

	//Menu D
	Translate( 0x009F2D5C, "Ignorados: %d / %d" );
	Translate( 0x009F2D58, "Amigos: %d / %d" );
	Translate( 0x009F2D54, "Recentes" );

	//Comandos GM
	Translate( 0x004AD8E5, "GM: Habilidades temporárias canceladas" );
	Translate( 0x004AD88D, "/cancelar_habilidades_temporarias" );
	Translate( 0x004AD859, "GM: Atalhos de Habilidades resetados" );
	Translate( 0x004AD83F, "/resetar_atalhos_habilidades" );
	Translate( 0x004AD5F1, "GM: Booster cancelado" );
	Translate( 0x004AD5DD, "/cancelar_booster" );
	Translate( 0x004AD4F2, "GM: Força Orb cancelada" );
	Translate( 0x004AD4DA, "/cancelar_forca_orb" );
	Translate( 0x004AD465, "/desconhecido_go" );
	Translate( 0x004AD3E6, "/desconhecido_come" );
	Translate( 0x004AD3AD, "GM: Desafio Ativo cancelado" );
	Translate( 0x004AD399, "/cancelar_desafio_ativo" );
	Translate( 0x004AD365, "GM: Você ainda não completou o 3° Desafio de Classe" );
	Translate( 0x004AD35E, "GM: Você ainda não está no Nível 80" );
	Translate( 0x004AD357, "GM: Faça a 4ª Parte do 4° Desafio de Classe" );
	Translate( 0x004AD327, "GM: Faça a 3ª Parte do 4° Desafio de Classe" );
	Translate( 0x004AD30D, "GM: Faça a 2ª Parte do 4° Desafio de Classe" );
	Translate( 0x004AD2F3, "GM: Faça a 1ª Parte do 4° Desafio de Classe" );
	Translate( 0x004AD287, "/desafio_de_classe_4" );
	Translate( 0x004AD212, "GM: Faça o Desafio agora" );
	Translate( 0x004AD253, "GM: Faça o Desafio agora" );
	Translate( 0x004AD1D1, "GM: Desafio de Classe completo" );
	Translate( 0x004AD1A7, "GM: Desafio de Classe completo" );
	Translate( 0x004AD175, "GM: Desafio de Classe completo" );
	Translate( 0x004AD115, "/terminar_desafio_de_classe" );
	Translate( 0x004AD0AD, "GM: Desafio de Classe completo" );
	Translate( 0x004AD099, "/completar_desafio_de_classe" );
	Translate( 0x004AD065, "GM: Retire seus itens no Distribuidor de Itens" );
	Translate( 0x004AD03F, "/distribuidor" );
	Translate( 0x004AD00B, "GM: Pontos de Atributos resetados" );
	Translate( 0x004ACFA0, "/resetar_atributos" );
	Translate( 0x004ACF6C, "GM: Pontos de Habilidades resetados" );
	Translate( 0x004ACF50, "/resetar_habilidades" );
	Translate( 0x004ACF1C, "GM: Você mudou de Nível" );
	Translate( 0x004ACEB4, "/nivel" );
	Translate( 0x004ACE44, "GM: Desafio O Ataque a Eura completo" );
	Translate( 0x004ACE23, "GM: Desafio Poder Máximo completo" );
	Translate( 0x004ACE02, "GM: Desafio A Maldição completo" );
	Translate( 0x004ACDD0, "GM: Desafio Lágrimas de Kália completo" );
	Translate( 0x004ACDAC, "GM: Desafio A Rebelião completo" );
	Translate( 0x004ACD7E, "GM: Desafio A Transformação completo" );
	Translate( 0x004ACD48, "GM: Desafio A Caverna completo" );
	Translate( 0x004ACD07, "GM: Desafio Por Ela completo" );
	Translate( 0x004ACC82, "/completar_desafio" );
	Translate( 0x004ACC3A, "GM: Desafio de Classe completo" );
	Translate( 0x004ACE6D, "GM: Desafio de Classe completo" );
	Translate( 0x004ACBEE, "/desafio_de_classe_2" );
	Translate( 0x004ACB91, "/desafio_de_classe_3" );
	Translate( 0x004ACB5D, "GM: Desafio completo" );
	Translate( 0x004ACB07, "/desafio_amanda" );
	Translate( 0x004ACAD3, "GM: Desafio 100 completo" );
	Translate( 0x004ACA2C, "/completar_desafio_100" );
	Translate( 0x004AC9C5, "GM: Itens removidos do Inventário" );
	Translate( 0x004AC96F, "/remover_itens" );
	Translate( 0x004AC932, "/hoho" );
	Translate( 0x008405E4, "GM: Eu sou muito legal!" );
	Translate( 0x008405E8, "GM: Estou me sentindo ótimo hoje!" );
	Translate( 0x008405EC, "GM: Ser GM é demais!" );
	Translate( 0x008405F0, "GM: Está um lindo dia, não está?" );
	Translate( 0x008405F4, "GM: Priston Tale - Returns é o melhor!" );
	Translate( 0x008405F8, "GM: Eu amo Priston Tale!" );
	Translate( 0x006396BC, "/caminho" );
	Translate( 0x0063968F, "/salvar" );
	Translate( 0x00639662, "/desconhecido_localizacao" );
	Translate( 0x006394DB, "/desconhecido_acesso" );
	Translate( 0x006394A2, "/MAPA" );
	Translate( 0x0063948C, "/mapa" );
	Translate( 0x0063946B, "/desconhecido_lago_do_crepusculo" );
	Translate( 0x0063942B, "/desconhecido_ren" );
	Translate( 0x006393F3, "/desconhecido_baload" );
	Translate( 0x006393BB, "/desconhecido_deload" );
	Translate( 0x00639382, "/cabelo" );
	Translate( 0x0063933B, "/desconhecido_mymodel" );
	Translate( 0x00639303, "/desconhecido_body" );
	Translate( 0x006392CB, "/desconhecido_char_load" );
	Translate( 0x0063928D, "/carregar_personagem" );
	Translate( 0x0063923C, "/desconhecido_broke_mem" );
	Translate( 0x006390B3, "/posicao" );
	Translate( 0x0063907B, "/absorcao" );
	Translate( 0x00639042, "/fala" );
	Translate( 0x00639017, "Armazém salvo" );
	Translate( 0x00638FEA, "/salvar_armazem" );
	Translate( 0x00638FBF, "Informações do Grupo: %d" );
	Translate( 0x00638F9A, "/informacoes_grupo" );
	Translate( 0x00638F65, "Experiência Perdida: %d %c" );
	Translate( 0x00638F56, "Experiência Ganha: %d %c" );
	Translate( 0x00638F0D, "/experiencia_porcento" );
	Translate( 0x00638EE2, "> Você ganhou %d de Experiência" );
	Translate( 0x00638EA0, "/experiencia_quantidade" );
	Translate( 0x00638D88, "/desconhecido_color" );
	Translate( 0x00638D2D, "/desconhecido_dark" );

	//Comandos Player
	Translate( 0x0045DFC4, "/clan " );
	Translate( 0x0041C848, "/clan %s" );
	Translate( 0x0041C868, "/troca %s" );
	Translate( 0x004173B4, "/grupo %s" );
	Translate( 0x00638E59, "/noticias" );
	Translate( 0x00638CF8, "/liga_camera" );
	Translate( 0x00638CD2, "/desliga_camera" );
	Translate( 0x00638CA4, "> Conexão: %dms" );
	Translate( 0x00638C4A, "/CONEXAO" );
	Translate( 0x00638C34, "/conexao" );
	Translate( 0x00638B73, "yahoo" );

	//Itens
	Translate( 0x0098E230, "Ataque:        \r" );
	Translate( 0x0098E234, "Vel. da Arma:  \r" );
	Translate( 0x0098E238, "Alcance:       \r" );
	Translate( 0x0098E23C, "Crítico:       \r" );
	Translate( 0x0098E240, "Defesa:        \r" );
	Translate( 0x0098E244, "Precisão:      \r" );
	Translate( 0x0098E248, "Absorção:      \r" );
	Translate( 0x0098E24C, "Bloqueio:      \r" );
	Translate( 0x0098E250, "Velocidade:    \r" );
	Translate( 0x0098E254, "Integridade:   \r" );
	Translate( 0x0098E258, "Rec. Mana:     \r" );
	Translate( 0x0098E25C, "Rec. de Vida:  \r" );
	Translate( 0x0098E260, "Rec. Estamina: \r" );
	Translate( 0x0098E264, "Res. a Terra:  \r" );
	Translate( 0x0098E26C, "Res. a Fogo:   \r" );
	Translate( 0x0098E270, "Res. a Gelo:   \r" );
	Translate( 0x0098E274, "Res. a Raio:   \r" );
	Translate( 0x0098E278, "Res. a Veneno: \r" );
	Translate( 0x0098E284, "Reg. Vida:     \r" );
	Translate( 0x0098E288, "Reg. Mana:     \r" );
	Translate( 0x0098E28C, "Reg. Estamina: \r" );
	Translate( 0x0098E290, "Vida:          \r" );
	Translate( 0x0098E294, "Mana:          \r" );
	Translate( 0x0098E298, "Estamina:      \r" );
	Translate( 0x0098E29C, "Poções:        \r" );
	Translate( 0x0098E2A0, "Nível:         \r" );
	Translate( 0x0098E2A4, "Força:         \r" );
	Translate( 0x0098E2A8, "Inteligência:  \r" );
	Translate( 0x0098E2AC, "Talento:       \r" );
	Translate( 0x0098E2B0, "Agilidade:     \r" );
	Translate( 0x0098E2B4, "Vitalidade:    \r" );
	Translate( 0x0098E3C0, "Spec %s\r" );
	Translate( 0x0098E2F8, "Vel. da Arma:  \r" );
	Translate( 0x0098E2FC, "Crítico:       \r" );
	Translate( 0x0098E300, "Defesa:        \r" );
	Translate( 0x0098E304, "Absorção:      \r" );
	Translate( 0x0098E308, "Bloqueio:      \r" );
	Translate( 0x0098E30C, "Bônus Mágico:  \r" );
	Translate( 0x0098E310, "Velocidade:    \r" );
	Translate( 0x0098E334, "Ataque:        \r" );
	Translate( 0x004CDB06, "NV/%d\r" );
	Translate( 0x0098E338, "Precisão:      \r" );
	Translate( 0x004CDB51, "NV/%d\r" );
	Translate( 0x0098E33C, "Alcance:       \r" );
	Translate( 0x0098E360, "Vida:          \r" );
	Translate( 0x004CDE4F, "NV/%d\r" );
	Translate( 0x0098E364, "Mana:          \r" );
	Translate( 0x004CDE9A, "NV/%d\r" );
	Translate( 0x0098E368, "Reg. Vida:     \r" );
	Translate( 0x0098E36C, "Reg. Mana:     \r" );
	Translate( 0x0098E370, "Reg. Estamina: \r" );
	Translate( 0x0098E374, "Preço:         \r" );
	Translate( 0x0098E378, "Preço:         \r" );

	//Monstros
	Translate( 0x0098E5C8, "Normal" );
	Translate( 0x0098E5C0, "Mecânico" );
	Translate( 0x0098E5C4, "Demônio" );
	Translate( 0x0098E5BC, "Mutante" );
	Translate( 0x0098E5CC, "Morto-Vivo" );

	//Habilidades
	Translate( 0x0098E460, "Preço:               \r" );
	Translate( 0x0098E3D0, "Ataque Padrão\r" );
	Translate( 0x0098E3D4, "%s (Nível Necessário: %d)\r" );
	Translate( 0x0098E7C4, "(Próximo Nível: %d)\r" );
	Translate( 0x0098E3D8, "Itens Compatíveis\r" );
	Translate( 0x0098E3CC, "Próximo Nível\r" );
	Translate( 0x0098E3F8, "Bloqueio:            \r" );
	Translate( 0x0098E3FC, "Duração:             \r" );
	Translate( 0x004F757A, "%d segundos\r" );
	Translate( 0x0098E410, " segundos" );
	Translate( 0x0098E400, "Mana:                \r" );
	Translate( 0x0098E45C, "Estamina:            \r" );
	Translate( 0x0098E404, "Ataque:              \r" );
	Translate( 0x0098E408, "Alcance:             \r" );
	Translate( 0x004F6F0A, "(%s, %s - %d%s %s" );
	Translate( 0x004F70A1, "(%s, %s - %d%s %s" );
	Translate( 0x004F721E, "(%s, %s - %d%s %s" );
	Translate( 0x0098E5D0, "Ataque Bônus)\r" );
	Translate( 0x0098E3DC, "Res. a Veneno:       \r" );
	Translate( 0x0098E40C, "Absorção:            \r" );
	Translate( 0x0098E450, "Precisão:            \r" );
	Translate( 0x0098E538, "Ataque Máximo:       \r" );
	Translate( 0x0098E3F0, "Ataque:              \r" );
	Translate( 0x0098E3EC, "Ataque Máximo:       \r" );
	Translate( 0x0098E3F4, "Vel. da Arma:        \r" );
	Translate( 0x0098E3E4, "Área:                \r" );
	Translate( 0x004F799D, "%d-%d+(NV)\r" );
	Translate( 0x004F6ED8, "(%s - %d%s %s" );
	Translate( 0x004F7043, "(%s - %d%s %s" );
	Translate( 0x004F718F, "(%s - %d%s %s" );
	Translate( 0x0098E668, "Defesa:              \r" );
	Translate( 0x0098E71C, ")\r" );
	Translate( 0x0098E724, "Absorção Física" );
	Translate( 0x004F6FBF, "(%s %d%s%s" );
	Translate( 0x004F7129, "(%s %d%s%s" );
	Translate( 0x004F71BA, "(%s %d%s%s" );
	Translate( 0x004F7277, "(%s %d%s%s" );
	Translate( 0x0098E7C0, "Dano Refletido:      \r" );
	Translate( 0x0098E5F4, "Defesa:              \r" );
	Translate( 0x0098E680, "Ataque:              \r" );
	Translate( 0x0098E520, "Alcance:             \r" );
	Translate( 0x0098E684, "Número de Ataques:   \r" );
	Translate( 0x0098E688, "Absorção:            \r" );
	Translate( 0x0098E68C, "Área:                \r" );
	Translate( 0x0098E690, "Ataque:              \r" );
	Translate( 0x0098E408, "Alcance:             \r" );
	Translate( 0x0098E65C, "Intervalo de Ataque: \r" );
	Translate( 0x0098ECDC, "Tipo de Ataque:      \r" );
	Translate( 0x0098ECE4, "Automático\r" );
	Translate( 0x0098ECE0, "Manual\r" );
	Translate( 0x0098E6C0, "Precisão:            \r" );
	Translate( 0x0098E694, "Vida:                \r" );
	Translate( 0x0098E6C4, "Defesa:              \r" );
	Translate( 0x0098E514, "Alcance:             \r" );
	Translate( 0x0098E3E0, "Res. a Fogo:         \r" );
	Translate( 0x0098E41C, "Número de Ataques:   \r" );
	Translate( 0x0098E420, "Redução de Vida:     \r" );
	Translate( 0x0098E424, "Precisão:            \r" );
	Translate( 0x0098E428, "Crítico:             \r" );
	Translate( 0x0098E4D8, "Área:                \r" );
	Translate( 0x0098E430, "Dano por Fogo:       \r" );
	Translate( 0x0098E730, "Precisão:            \r" );
	Translate( 0x0098E72C, "Girada Brutal - Crítico" );
	Translate( 0x0098E4E8, "Precisão:            \r" );
	Translate( 0x0098E5F8, "Bônus vs Demônio:    \r" );
	Translate( 0x0098E418, "Ataque:              \r" );
	Translate( 0x0098E698, "Absorção:            \r" );
	Translate( 0x0098E69C, "Bônus de Ataque:     \r" );
	Translate( 0x0098E6A0, "Número de Ataques:   \r" );
	Translate( 0x0098E6A4, "Vida:                \r" );
	Translate( 0x0098E42C, "Área:                \r" );
	Translate( 0x0098E434, "Res. a Gelo:         \r" );
	Translate( 0x0098E438, "Ataque:              \r" );
	Translate( 0x0098E480, "Duração:             \r" );
	Translate( 0x0098E440, "Bloqueio:            \r" );
	Translate( 0x0098E444, "Tamanho:             \r" );
	Translate( 0x0098E604, "Duração:             \r" );
	Translate( 0x0098E600, "Número de Ataques:   \r" );
	Translate( 0x0098E5FC, "Ataque:              \r" );
	Translate( 0x0098E4AC, "\r" );
	Translate( 0x0098E67C, "Visibilidade:        \r" );
	Translate( 0x0098E678, "Bônus do 1° Ataque:  \r" );
	Translate( 0x0098E608, "Crítico:             \r" );
	Translate( 0x0098E6B8, "Número de Ataques:   \r" );
	Translate( 0x0098E6B4, "Esquiva:             \r" );
	Translate( 0x0098E6B0, "Bônus se Carregar:   \r" );
	Translate( 0x0098E6AC, "Crítico do Oponente: \r" );
	Translate( 0x0098E6A8, "Crítico:             \r" );
	Translate( 0x0098ECD0, "Vel. para Carregar:  \r" );
	Translate( 0x0098E468, "Ataque:              \r" );
	Translate( 0x0098E718, "Ataque:              \r" );
	Translate( 0x0098E448, "Número de Voltas:    \r" );
	Translate( 0x0098E478, "" );
	Translate( 0x0098E44C, "Vel. da Arma:        \r" );
	Translate( 0x004FA210, "%d+(NV/%d)\r" );
	Translate( 0x004FA49F, "NV/%d\r" );
	Translate( 0x0098E458, "Número de Ataques:   \r" );
	Translate( 0x0098E504, "Ataque de Raio:      \r" );
	Translate( 0x0098E4FC, "Ataque de Fogo:      \r" );
	Translate( 0x0098E610, "Reg. de Vida:        \r" );
	Translate( 0x0098E60C, "Ataque do Falcão:    \r" );
	Translate( 0x0098E614, "Dano em Área:        \r" );
	Translate( 0x0098E4F4, "Alcance:             \r" );
	Translate( 0x0098E6BC, "Vida:                \r" );
	Translate( 0x0098E6C8, "Esquiva:             \r" );
	Translate( 0x0098E6CC, "Ataque:              \r" );
	Translate( 0x0098E6D0, "Alcance:             \r" );
	Translate( 0x004FB05F, "%d-%d+(NV/2)\r" );
	Translate( 0x0098E49C, "Estamina:            \r" );
	Translate( 0x0098E4E0, "Alcance:             \r" );
	Translate( 0x0098E628, "Bônus vs Morto-Vivo: \r" );
	Translate( 0x0098E4E4, "Área:                \r" );
	Translate( 0x0098E4EC, "Alcance:             \r" );
	Translate( 0x0098E4F0, "Defesa:              \r" );
	Translate( 0x0098E61C, "Dano Convertido:     \r" );
	Translate( 0x0098E620, "Chance de Sucesso:   \r" );
	Translate( 0x0098E624, "Vida Adicional:      \r" );
	Translate( 0x0098E738, "Escudo Divino - Bloqueio" );
	Translate( 0x0098E6E0, "Absorção:            \r" );
	Translate( 0x0098E62C, "Número de Ataques:   \r" );
	Translate( 0x0098E498, "(Ataque com Escudo)\r" );
	Translate( 0x004FC0B3, "%d-%d+(NV)\r" );
	Translate( 0x004FC036, "+(NV)" );
	Translate( 0x0098E4C8, "Ataque:              \r" );
	Translate( 0x004FC338, "%d-%d+(NV/2)\r" );
	Translate( 0x0098E534, "Ataque:              \r" );
	Translate( 0x0098E4F8, "Dano Convertido:     \r" );
	Translate( 0x0098E5D4, "Ataque de Fogo)\r" );
	Translate( 0x004FC4B8, "%d-%d+(NV/3)\r" );
	Translate( 0x004FC616, "%d-%d+(NV/3)\r" );
	Translate( 0x0098E634, "Ataque Máximo:       \r" );
	Translate( 0x004FC4FB, "%d+(NV/4)\r" );
	Translate( 0x0098E638, "Ataque:              \r" );
	Translate( 0x0098E734, "Triunfo de Valhala -" );
	Translate( 0x0098E6E4, "Área:                \r" );
	Translate( 0x0098ECD4, "Ataque:              \r" );
	Translate( 0x0098ECD8, "Congelamento:        \r" );
	Translate( 0x0098E6E8, "Redução da Veloc.:   \r" );
	Translate( 0x0098E4A0, "Rec. de Vida:        \r" );
	Translate( 0x0098E4D0, "Ataque:              \r" );
	Translate( 0x0098E4D4, "Número de Ataques:   \r" );
	Translate( 0x0098E4B0, "Redução do Ataque:   \r" );
	Translate( 0x0098E508, "Reg. de Mana:        \r" );
	Translate( 0x0098E50C, "Número de Ataques:   \r" );
	Translate( 0x0098E510, "Dano Refletido:      \r" );
	Translate( 0x0098E63C, "Chance de Sucesso:   \r" );
	Translate( 0x0098E648, "Chance de Sucesso:   \r" );
	Translate( 0x0098E64C, "Redução de Vida:     \r" );
	Translate( 0x0098E650, "Vida:                \r" );
	Translate( 0x0098E6F0, "Reg. de Mana:        \r" );
	Translate( 0x0098E6EC, "Reg. de Vida:        \r" );
	Translate( 0x0098E6F4, "Área:                \r" );
	Translate( 0x0098E6FC, "Alcance:             \r" );
	Translate( 0x0098E6F8, "Número de Ataques:   \r" );
	Translate( 0x0098E700, "Absorção:            \r" );
	Translate( 0x0098E704, "Esquiva:             \r" );
	Translate( 0x004FD8CF, "%d+(NV/5)%s\r" );
	Translate( 0x0098E4B4, "Mana Convertida:     \r" );
	Translate( 0x0098E4B8, "Resistências:        \r" );
	Translate( 0x0098E518, "Mana:                \r" );
	Translate( 0x0098E500, "Ataque de Gelo:      \r" );
	Translate( 0x0098E654, "Dano Convertido:     \r" );
	Translate( 0x0098E658, "Ataque:              \r" );
	Translate( 0x0098E664, "Ataque de Gelo:      \r" );
	Translate( 0x0098E660, "Ataque de Fogo:      \r" );
	Translate( 0x0098E70C, "Ataque:              \r" );
	Translate( 0x0098E710, "Redução da Veloc.:   \r" );
	Translate( 0x0098E714, "Redução do Ataque:   \r" );

	//Portal
	Translate( 0x0098E574, "Portal" );
	Translate( 0x0098E578, "Ricarten" );
	Translate( 0x0098E57C, "Pilai" );
	Translate( 0x0098E580, "Floresta das Ilusões" );
	Translate( 0x0098E584, "Floresta de Bambu" );
	Translate( 0x0098E588, "Vila Ruinen" );
	Translate( 0x0098E58C, "Navisco" );
	Translate( 0x0098E590, "Terra Proibida" );
	Translate( 0x0098E594, "Eura" );
	Translate( 0x0098E5D8, "Castelo Sagrado" );

	//Controlador Cameron
	Translate( 0x0098ED70, "Concluído" );
	Translate( 0x0098E960, "Preço: " );
	Translate( 0x0098E95C, "Preço: " );
	Translate( 0x0098E958, "Cristal de Raio" );
	Translate( 0x0098E954, "ataques de gelo" );
	Translate( 0x0098E950, "Atordoa os inimigos usando" );
	Translate( 0x0098E94C, "Cristal de Raio" );
	Translate( 0x0098E948, "Cristal de Fogo" );
	Translate( 0x0098E944, "ataques de fogo" );
	Translate( 0x0098E940, "Destrói os inimigos usando" );
	Translate( 0x0098E93C, "Cristal de Fogo" );
	Translate( 0x0098E938, "Cristal de Gelo" );
	Translate( 0x0098E934, "ataques de gelo" );
	Translate( 0x0098E930, "Atrasa os inimigos usando" );
	Translate( 0x0098E92C, "Cristal de Gelo" );
	Translate( 0x0098E928, "Total: %d / 20" );
	Translate( 0x0098E924, "treinados para a guerra" );
	Translate( 0x0098E920, "Os Soldados de Ricarten são" );
	Translate( 0x0098E91C, "Soldado de Ricarten" );
	Translate( 0x0098E918, "Total: %d / 20" );
	Translate( 0x0098E914, "treinados para defender o Castelo" );
	Translate( 0x0098E910, "Os Soldados do Castelo são" );
	Translate( 0x0098E90C, "Soldado do Castelo" );
	Translate( 0x0098E8F8, "Total: %d / 20" );
	Translate( 0x0098E8F4, "treinados para o combate" );
	Translate( 0x0098E8F0, "Os Milícias de Ricarten são" );
	Translate( 0x0098E8EC, "Milícia de Ricarten" );
	Translate( 0x0098E8E8, "A taxa atual é %d%s" );
	Translate( 0x0098E8E4, "Você deseja retirar Ouro?" );
	Translate( 0x0098E8E0, " Ouro" );
	Translate( 0x0098ECE8, " Ouro" );
	Translate( 0x0098E8DC, "Total de Ouro acumulado" );
	Translate( 0x0098E8D8, "A nova taxa será %d%s" );

	//Evento Castelo Sagrado
	Translate( 0x0098F444, "Castelo Sagrado" );
	Translate( 0x0098F43C, "Tempo: " );
	Translate( 0x0098F438, "P.B: " );
	Translate( 0x0098F430, "Pontos de Batalha: " );
	Translate( 0x0098F440, "Hit Rate: " );
	Translate( 0x0098F434, "Con Rate: " );

	//Bellatra
	Translate( 0x0098E964, "Líder" );
	Translate( 0x0098E8B8, "A taxa atual é %d%s" );
	Translate( 0x0098E8B4, "adquirido pelos guerreiros durante o desafio." );
	Translate( 0x0098E8B0, "O Clã líder de Bellatra recebe parte do Ouro" );
	Translate( 0x0098E8C0, "O Líder do Clã pode retirar o Ouro acumulado." );
	Translate( 0x0098E8BC, "Parabéns! O seu Clã é o líder de Bellatra." );
	Translate( 0x0098E8CC, "Clique em Retirar para retirar o Ouro acumulado." );
	Translate( 0x0098E8C8, "O Clã receberá parte do Ouro adquirido." );
	Translate( 0x0098E8C4, "Parabéns! O seu Clã é o líder de Bellatra." );

	//Habilidades
	Translate( 0x0098E20C, "Pontos Especiais: %d" );
	Translate( 0x0098E208, "Pontos Simples: %d" );
	Translate( 0x0098E1F0, "Habilidades para treinar." );
	Translate( 0x0098E1EC, "Você não tem Pontos de" );
	Translate( 0x0098E1E8, "aprender ou melhorar." );
	Translate( 0x0098E1E4, "Escolha uma Habilidade para" );
	Translate( 0x0098E1E0, "Habilidades" );

	//Tela de Morte
	Translate( 0x0098E1C0, "Voltar para o Campo" );
	Translate( 0x0098E1D0, "Custa Experiência e Ouro" );
	Translate( 0x0098E1CC, "Você não tem Ouro" );
	Translate( 0x0098E1DC, "ou Experiência" );
	Translate( 0x0098E1C4, "Voltar para a Cidade" );
	Translate( 0x0098E1C8, "Sair" );

	//Sábio Newter
	Translate( 0x0098E528, "Desafio" );
	Translate( 0x0098EAEC, "Mata das Acácias/Caverna dos Cogumelos" );
	Translate( 0x0098EAF0, "Floresta das Ilusões/Caverna das Abelhas" );
	Translate( 0x0098EAF4, "Terra Maldita/Calabouço Antigo" );
	Translate( 0x0098EAF8, "Terra Proibida/Estrada de Ferro do Caos" );

	//Desafios	
	Translate( 0x005B1C2A, "Cancelar Desafio" );

	Translate( 0x00836BF8, "Vigia Cansado" );
	Translate( 0x00836C08, "Vigia Cansado" );
	Translate( 0x00836BFC, "Vigia Cansado" );
	Translate( 0x00836C0C, "Vigia Cansado" );
	Translate( 0x004A27B4, "Vigia Cansado" );
	Translate( 0x00836C18, "Primeira Caça" );
	Translate( 0x00836C28, "Primeira Caça" );
	Translate( 0x00836C1C, "Primeira Caça" );
	Translate( 0x00836C2C, "Primeira Caça" );
	Translate( 0x004A2894, "Primeira Caça" );
	Translate( 0x00836C38, "Doce Especial" );
	Translate( 0x00836C48, "Doce Especial" );
	Translate( 0x00836C3C, "Doce Especial" );
	Translate( 0x00836C4C, "Doce Especial" );
	Translate( 0x00836C58, "Invasão dos Duendes" );
	Translate( 0x00836C68, "Invasão dos Duendes" );
	Translate( 0x00836C5C, "Invasão dos Duendes" );
	Translate( 0x00836C6C, "Invasão dos Duendes" );
	Translate( 0x00836C78, "Morto-Vivo" );
	Translate( 0x00836C88, "Morto-Vivo" );
	Translate( 0x00836C7C, "Morto-Vivo" );
	Translate( 0x00836C8C, "Morto-Vivo" );
	Translate( 0x00836C9C, "Destruição dos Cíclopes" );
	Translate( 0x00836C98, "Destruição dos Cíclopes" );
	Translate( 0x00836CAC, "Martelo Perdido" );
	Translate( 0x00836CA8, "Martelo Perdido" );
	Translate( 0x0083697C, "1° Desafio de Classe" );
	Translate( 0x0083698C, "1° Desafio de Classe" );
	Translate( 0x0083699C, "1° Desafio de Classe" );
	Translate( 0x008369BC, "1° Desafio de Classe" );
	Translate( 0x00836978, "1° Desafio de Classe" );
	Translate( 0x008369BC, "1° Desafio de Classe" );
	Translate( 0x00836A5C, "Por Ela" );
	Translate( 0x00836A58, "Por Ela" );
	Translate( 0x004A15E6, "Por Ela" );
	Translate( 0x008369B8, "2° Desafio de Classe" );
	Translate( 0x008369C8, "2° Desafio de Classe" );
	Translate( 0x008369AC, "2° Desafio de Classe" );
	Translate( 0x00836998, "2° Desafio de Classe" );
	Translate( 0x00836A6F, "A Caverna" );
	Translate( 0x00836A7F, "A Caverna" );
	Translate( 0x00836A68, "A Caverna" );
	Translate( 0x00836A78, "A Caverna" );
	Translate( 0x00836A1C, "3° Desafio de Classe" );
	Translate( 0x00836A18, "5ª Parte" );
	Translate( 0x00836A0C, "4ª Parte" );
	Translate( 0x00836A08, "3ª Parte" );
	Translate( 0x008469FC, "2ª Parte" );
	Translate( 0x008369F8, "1ª Parte" );
	Translate( 0x00836A8C, "Transformação de Monstros" );
	Translate( 0x00836A88, "Transformação de Monstros" );
	Translate( 0x00836A9C, "A Rebelião" );
	Translate( 0x00836A98, "A Rebelião" );
	Translate( 0x00836ACC, "Maldição do Poder" );
	Translate( 0x00836ADC, "Maldição do Poder" );
	Translate( 0x00836AEC, "Maldição do Poder" );
	Translate( 0x00836AC8, "Maldição do Poder" );
	Translate( 0x00836ADB, "Maldição do Poder" );
	Translate( 0x00836AEB, "Maldição do Poder" );
	Translate( 0x00836AAC, "Lágrimas de Kália" );
	Translate( 0x00836AA8, "Lágrimas de Kália" );
	Translate( 0x00836AB8, "Ataque a Eura" );
	Translate( 0x00836ABC, "Ataque a Eura" );
	Translate( 0x00836AFC, "Poder Máximo" );
	Translate( 0x00836B0C, "Poder Máximo" );
	Translate( 0x00836B1C, "Poder Máximo" );
	Translate( 0x00836B2C, "Poder Máximo" );
	Translate( 0x00836AF8, "Poder Máximo" );
	Translate( 0x00836B08, "Poder Máximo" );
	Translate( 0x00836B18, "Poder Máximo" );
	Translate( 0x00836B28, "Poder Máximo" );
	Translate( 0x00836CDC, "A Ilusão" );
	Translate( 0x00836CD8, "5ª Parte" );
	Translate( 0x00836CCC, "4ª Parte" );
	Translate( 0x00836CC8, "3ª Parte" );
	Translate( 0x00836CBC, "2ª Parte" );
	Translate( 0x00836CB8, "1ª Parte" );
}

void CSkillTranslate::SetTranslations( )
{
	Name( "Escudo Extremo" );
	Description( " Aumenta o Bloqueio do Escudo  temporariamente" );
	Name( "Bomba Mecânica" );
	Description( "Joga uma bomba que explode nos inimigos ao redor" );
	Name( "Resistência a Veneno" );
	Description( "Aumenta a Resistência a Veneno permanentemente" );
	Name( "Absorção Física" );
	Description( "        Aumenta a Absorção     temporariamente" );
	Name( "Golpe Grande" );
	Description( " Carrega e desfere um poderoso golpe nos inimigos ao redor" );
	Name( "Maximizar" );
	Description( "Aumenta temporariamente o Poder    de Ataque Máximo da Arma   equipada" );
	Name( "Automação" );
	Description( "  Aperfeiçoa o uso de Lanças e   Arcos, aumentando o Poder de Ataque e a Velocidade do Ataquetemporariamente" );
	Name( "Spark" );
	Description( "   Cria uma esfera de energia       concentrada e lança nos   inimigos" );
	Name( "Armadura Metálica" );
	Description( "    Aumenta temporariamente a   Defesa se a armadura equipada possuir Spec Mecânico" );
	Name( "Golpe Grandioso" );
	Description( "      Ataca o inimigo com dois  poderosos ataques com Taxa de       Ataque e Poder de Ataque adicionais" );
	Name( "Mestre das Armas Mecânicas" );
	Description( "Aumenta permanentemente o Poder      de Ataque das armas que  possuírem Spec Mecânico" );
	Name( "Escudo Spark" );
	Description( " Cria um escudo de energia que      enviará todos os ataques     bloqueados de volta para o  inimigo" );
	Name( "Impulso" );
	Description( "Cria um corrente de sparks que      atacará vários inimigos aomesmo tempo" );
	Name( "Implosão" );
	Description( " Cria um campo magnético que       atrai os inimigos ao redor       e aumenta a Absorção     temporariamente" );
	Name( "Esferas Magnéticas" );
	Description( " Cria 3 esferas magnéticas que     atacarão os inimigos mais  próximos" );
	Name( "Golem de Metal" );
	Description( " Cria um Golem de Metal gigante      que ajudará atacando os  inimigos" );
	Name( "T5_1_MS" );
	Description( "T5_1_MS" );
	Name( "T5_2_MS" );
	Description( "T5_2_MS" );
	Name( "T5_3_MS" );
	Description( "T5_3_MS" );
	Name( "T5_4_MS" );
	Description( "T5_4_MS" );
	Name( "Mestre das Armas" );
	Description( "    Aumenta o Poder de Ataque  permanentemente" );
	Name( "Resistência a Fogo" );
	Description( "  Aumenta a Resistência a Fogo permanentemente" );
	Name( "Raiva" );
	Description( "Ataca várias vezes com Poder de Ataque adicional, porém perde parte da própria Vida" );
	Name( "Impacto" );
	Description( "Aumenta o Poder de Ataque e a  Taxa de Ataque para derrubar o inimigo" );
	Name( "Impacto Triplo" );
	Description( "    Uma versão mais forte do   Impacto" );
	Name( "Girada Brutal" );
	Description( "Desfere um forte e fatal ataqueno oponente" );
	Name( "Rugido" );
	Description( "  Libera um grande rugido para       atordoar e confundir os  inimigos temporariamente" );
	Name( "Fúria de Zecram" );
	Description( "Ataca utilizando as habilidadesdo lendário herói Zecram" );
	Name( "Concentração" );
	Description( "    Aumenta a Taxa de Ataque   temporariamente" );
	Name( "Golpe da Vingança" );
	Description( "   Vinga-se do inimigo com um  ataque poderoso" );
	Name( "Machado Veloz" );
	Description( "Aumenta a Velocidade do Machadotemporariamente" );
	Name( "Quebra Ossos" );
	Description( "   Derruba o oponente com um   poderoso ataque" );
	Name( "Destroyer" );
	Description( " Acerta o inimigo 3 vezes com opoder de um Destroyer" );
	Name( "Fúria" );
	Description( "   Aumenta o Poder de Ataque   sacrificando parte da Absorção" );
	Name( "Golpe Giratório" );
	Description( "    Cria um ciclone para abatervários inimigos ao mesmo tempo" );
	Name( "Bônus de Vida" );
	Description( "Aumenta a Vida permanentemente" );
	Name( "T5_1_FS" );
	Description( "T5_1_FS" );
	Name( "T5_2_FS" );
	Description( "T5_2_FS" );
	Name( "T5_3_FS" );
	Description( "T5_3_FS" );
	Name( "T5_4_FS" );
	Description( "T5_4_FS" );
	Name( "Sopro Afiado" );
	Description( "Cria um vento circular com sua foice, afastando os inimigos" );
	Name( "Resistência a Gelo" );
	Description( "  Aumenta a Resistência a Gelo permanentemente" );
	Name( "Ataque Crítico" );
	Description( "    Acerta os pontos fracos do inimigo causando danos críticos" );
	Name( "Pulo Fatal" );
	Description( "  Com um salto, ataca com um   golpe concentrado" );
	Name( "Espinhos de Gelo" );
	Description( "     Enfia a foice no chão para         congelar e paralisar   temporariamente os inimigos ao redor" );
	Name( "Tornado" );
	Description( " Gira a foice como um tornado,   acertando vários inimigos ao mesmo tempo" );
	Name( "Mestre da Defesa" );
	Description( "         Aumenta o Bloqueio    permanentemente, quando estiverusando armas de duas mãos" );
	Name( "Expansão" );
	Description( "Aumenta o tamanho da arma para atacar com mais Poder de Ataque" );
	Name( "Lanças Venenosas" );
	Description( "     Enfia a foice no chão para  envenenar temporariamente os inimigos ao redor" );
	Name( "Desaparecer" );
	Description( "Desaparece temporariamente" );
	Name( "Mestre do Crítico" );
	Description( "           Aumenta o Crítico   permanentemente" );
	Name( "Foice de Aço" );
	Description( "Salta e ataca o oponente com umcombo triplo" );
	Name( "Olho Assassino" );
	Description( "Torna o inimigo mais vulnerávela ataques críticos" );
	Name( "Golpe Carregado" );
	Description( "Concentra-se para desferir um  golpe triplo letal" );
	Name( "Furtivo" );
	Description( "         Aumenta a Esquiva     temporariamente" );
	Name( "Mestre das Sombras" );
	Description( "Com o poder das sombra, ataca  o inimigo várias vezes" );
	Name( "T5_1_PS" );
	Description( "T5_1_PS" );
	Name( "T5_2_PS" );
	Description( "T5_2_PS" );
	Name( "T5_3_PS" );
	Description( "T5_3_PS" );
	Name( "T5_4_PS" );
	Description( "T5_4_PS" );
	Name( "Falcão Vigia" );
	Description( " Invoca um Falcão para vigiar a   área e aumentar a Taxa de   Ataque temporariamente" );
	Name( "Mestra do Tiro" );
	Description( "   Aumenta o Poder de Ataque   permanentemente" );
	Name( "Flecha de Vento" );
	Description( "Dispara uma flecha de vento commais Velocidade" );
	Name( "Mira Perfeita" );
	Description( "   Atira uma flecha perfeita no    alvo, com Taxa de Ataque   adicional" );
	Name( "Olho de Dion" );
	Description( " Treina a pontaria aumentando aTaxa de Ataque permanentemente" );
	Name( "Falcão" );
	Description( "Invoca um Falcão para ajudar a atacar o inimigo" );
	Name( "Flecha da Fúria" );
	Description( "    Lança no ar uma rajada de  flechas que explode e acerta osinimigos ao redor" );
	Name( "Avalanche" );
	Description( "Atira uma sequência de flechas perfurantes no inimigo" );
	Name( "Tiro Elemental" );
	Description( "Dispara um tiro de fogo ou raiocausando dano nos inimigos ao  redor" );
	Name( "Falcão Dourado" );
	Description( "Invoca um Falcão Dourado para      ajudar a atacar o inimigo e  aumentar sua Regeneração de  Vida temporariamente" );
	Name( "Tiro Explosivo" );
	Description( "  Atira duas flechas explosivas causando dano nos inimigos ao  edor" );
	Name( "Perfuração" );
	Description( "    Atira uma flecha precisa e poderosa que atravessa todos osinimigos no alcance do ataque" );
	Name( "Wolverine" );
	Description( "Invoca um Wolverine para ajudara atacar o inimigo" );
	Name( "Mestra da Esquiva" );
	Description( "         Aumenta a Esquiva     permanentemente" );
	Name( "Tiro Fênix" );
	Description( "Atira uma flecha encantada com as penas da lendária Fênix" );
	Name( "Força da Natureza" );
	Description( " Aumenta seu Poder de Ataque e  Taxa de Ataque usando a Força da Natureza" );
	Name( "T5_1_AS" );
	Description( "T5_1_AS" );
	Name( "T5_2_AS" );
	Description( "T5_2_AS" );
	Name( "T5_3_AS" );
	Description( "T5_3_AS" );
	Name( "T5_4_AS" );
	Description( "T5_4_AS" );
	Name( "T1_1_ASS" );
	Description( "T1_1_ASS" );
	Name( "T1_2_ASS" );
	Description( "T1_2_ASS" );
	Name( "T1_3_ASS" );
	Description( "T1_3_ASS" );
	Name( "T1_4_ASS" );
	Description( "T1_4_ASS" );
	Name( "T2_1_ASS" );
	Description( "T2_1_ASS" );
	Name( "T2_2_ASS" );
	Description( "T2_2_ASS" );
	Name( "T2_3_ASS" );
	Description( "T2_3_ASS" );
	Name( "T2_4_ASS" );
	Description( "T2_4_ASS" );
	Name( "T3_1_ASS" );
	Description( "T3_1_ASS" );
	Name( "T3_2_ASS" );
	Description( "T3_2_ASS" );
	Name( "T3_3_ASS" );
	Description( "T3_3_ASS" );
	Name( "T3_4_ASS" );
	Description( "T3_4_ASS" );
	Name( "T4_1_ASS" );
	Description( "T4_1_ASS" );
	Name( "T4_2_ASS" );
	Description( "T4_2_ASS" );
	Name( "T4_3_ASS" );
	Description( "T4_3_ASS" );
	Name( "T4_4_ASS" );
	Description( "T4_4_ASS" );
	Name( "T5_1_ASS" );
	Description( "T5_1_ASS" );
	Name( "T5_2_ASS" );
	Description( "T5_2_ASS" );
	Name( "T5_3_ASS" );
	Description( "T5_3_ASS" );
	Name( "T5_4_ASS" );
	Description( "T5_4_ASS" );
	Name( "Rajada Sagrada" );
	Description( "Carrega sua espada com a força   divina e lança uma rajada nosoponentes" );
	Name( "Corpo Sagrado" );
	Description( "Recebe uma energia sagrada para    aumentar a Absorção contra          monstros Morto-Vivo   temporariamente" );
	Name( "Treinamento Físico" );
	Description( " Treina o corpo para aumentar aEstamina permanentemente" );
	Name( "Golpe Duplo" );
	Description( " Um ataque duplo, veloz e letalcom altas chances de Crítico" );
	Name( "Valor Sagrado" );
	Description( "Aumenta temporariamente o Poder     de Ataque do grupo contra monstros Morto-Vivo" );
	Name( "Brandish" );
	Description( "    Com um salto, corta o chão causando dano em área" );
	Name( "Piercing" );
	Description( " Carrega sua espada desferindo     um golpe que atravessa os  inimigos no alcance do ataque" );
	Name( "Espírito Drástico" );
	Description( "      Concentra o espírito do      Cavaleiro para aumentar a  Defesa temporariamente" );
	Name( "Mestre da Espada" );
	Description( "  Treina o uso de Espadas para    aumentar o Poder de Ataque  permanentemente" );
	Name( "Escudo Divino" );
	Description( "         Aumenta o Bloqueio        temporariamente e converte ataques bloqueados de monstros  Morto-Vivo em Vida" );
	Name( "Encantamento Sagrado" );
	Description( "       Lança um feitiço para    escravizar monstros Morto-Vivo       para ajudar na batalha  temporariamente" );
	Name( "Grande Cruzada" );
	Description( "Uma cruzada sagrada poderosa,  veloz e contínua" );
	Name( "Piercing Divino" );
	Description( "     Utilizando a força divina, desfere uma sequência letal degolpes no inimigo" );
	Name( "Escudo dos Deuses" );
	Description( "    Usa o Escudo dos Deuses,        aumentando a Absorção     temporariamente" );
	Name( "Bênção Divina" );
	Description( " Com o poder da Bênção Divina  dos Deuses, aumenta o Poder de Ataque temporariamente" );
	Name( "Espada Justiceira" );
	Description( "   Ataca o chão com a espada       criando uma onda de fogo        sagrado para destruir os  inimigos" );
	Name( "T5_1_KS" );
	Description( "T5_1_KS" );
	Name( "T5_2_KS" );
	Description( "T5_2_KS" );
	Name( "T5_3_KS" );
	Description( "T5_3_KS" );
	Name( "T5_4_KS" );
	Description( "T5_4_KS" );
	Name( "Golpe do Escudo" );
	Description( "Ataca o inimigo com o escudo" );
	Name( "Farina" );
	Description( "       Atira a lança com mais  Velocidade e Taxa de Ataque" );
	Name( "Mestra do Arremesso" );
	Description( "  Aumenta a proficiência no usoda lança, aumentando o Poder deAtaque permanentemente" );
	Name( "Lança Gigante" );
	Description( "   Atira no inimigo uma lança  gigante" );
	Name( "Windy" );
	Description( "Adiciona a propriedade do vento para aumentar a Taxa de Ataque       e o Alcance do Ataque   temporariamente" );
	Name( "Lança Giratória" );
	Description( " Atira uma lança giratória paraderrubar os inimigos" );
	Name( "Ladrão de Almas" );
	Description( "Usa o escudo para absorver Vidados inimigos" );
	Name( "Lança de Fogo" );
	Description( "   Atira uma lança de fogo paraqueimar o oponente" );
	Name( "Lança Partida" );
	Description( "    Atira uma lança no ar que     separa em várias caindo e   atingindo o alvo em cheio" );
	Name( "Triunfo de Valhala" );
	Description( "   Com os poderes de Valhala,     aumenta o Poder de Ataque   Máximo temporariamente" );
	Name( "Lança de Raios" );
	Description( "       Atira uma lança com     propriedades de raio" );
	Name( "Chuva de Lanças" );
	Description( "       Arremessa duas lanças    devastadoras criando uma chuvaque destrói tudo em seu caminho" );
	Name( "Inferno de Valhala" );
	Description( "         Aumenta a Esquiva     temporariamente, além de ativar     os efeitos do Triunfo de  Valhala" );
	Name( "Fúria X" );
	Description( "   Pula no ar e atira 3 lanças  explosivas, atingindo todos osinimigos ao redor do ataque" );
	Name( "Lança de Gelo" );
	Description( "  Encanta todas as lanças com  propriedades do gelo, reduzindoa Velocidade dos inimigos" );
	Name( "Vingança" );
	Description( "Arremessa duas lanças com muitaforça, decapitando o alvo" );
	Name( "T5_1_ATS" );
	Description( "T5_1_ATS" );
	Name( "T5_2_ATS" );
	Description( "T5_2_ATS" );
	Name( "T5_3_ATS" );
	Description( "T5_3_ATS" );
	Name( "T5_4_ATS" );
	Description( "T5_4_ATS" );
	Name( "Cura" );
	Description( "  Com o poder divino, recupera sua Vida ou de seu aliado" );
	Name( "Fagulha Sagrada" );
	Description( "Atira uma fagulha com energia  divina para desintegrar o alvo" );
	Name( "Espinhos Múltiplos" );
	Description( "   Dispara um ataque múltiplo econcentrado em um único alvo" );
	Name( "Feitiço Divino" );
	Description( " Encanta o inimigo, reduzindo o       Poder de Ataque dele    temporariamente" );
	Name( "Meditação" );
	Description( "Com poderes sagrados, aumenta a        Regeneração de Mana    permanentemente" );
	Name( "Raios Divinos" );
	Description( "     Invoca uma chuva de raios     divinos para atingir váriosinimigos ao mesmo tempo" );
	Name( "Reflexão Divina" );
	Description( "Cria um escudo para refletir osataques dos monstros Morto-Vivo" );
	Name( "Cura Máxima" );
	Description( "Recupera parte da Vida de todos os membros do grupo dentro do alcance" );
	Name( "Esferas de Vigor" );
	Description( "Dispara duas esferas luminosas e letais contra o oponente" );
	Name( "Ressureição" );
	Description( "  Com poderes sagrados, tenta    trazer um membro do grupo de volta à Vida" );
	Name( "Extinção" );
	Description( " Lança um feitiço para reduzir    parte da Vida de monstros   Morto-Vivo" );
	Name( "Vida Virtual" );
	Description( "Aumenta a Vida temporariamente" );
	Name( "Espinhos Glaciais" );
	Description( "     Lâminas afiadas de gelo     projetam do chão atacando e  congelando os inimigos" );
	Name( "Campo de Regeneração" );
	Description( " Cria um campo para aumentar a  Regeneração de Vida e Mana de todos dentro do alcance" );
	Name( "Raios Contínuos" );
	Description( "   Cria uma corrente de ataques      elétricos atacando váriosinimigos ao mesmo tempo" );
	Name( "Muspell" );
	Description( "  Invoca um anjo celestial para     atacar e proteger contra  monstros Morto-Vivo" );
	Name( "T5_1_PRS" );
	Description( "T5_1_PRS" );
	Name( "T5_2_PRS" );
	Description( "T5_2_PRS" );
	Name( "T5_3_PRS" );
	Description( "T5_3_PRS" );
	Name( "T5_4_PRS" );
	Description( "T5_4_PRS" );
	Name( "Agonia" );
	Description( "Sacrifica parte da própria Vidapara recuperar parte da Mana" );
	Name( "Fagulha" );
	Description( "Dispara uma pequena fagulha de fogo para ferir o inimigo" );
	Name( "Zenith" );
	Description( " Aumenta temporariamente as      Resistências para todos os   tipos de elementos" );
	Name( "Bola de Fogo" );
	Description( "Lança uma bola de fogo gigante para abater o alvo" );
	Name( "Mestre da Mente" );
	Description( "Aumenta a Mana permanentemente" );
	Name( "Tornado de Água" );
	Description( "   Cria um poderoso tornado de água que explode nos inimigos" );
	Name( "Encanto" );
	Description( " Encanta a arma com fogo, gelo, ou raio, aumentando o Poder deAtaque termporariamente" );
	Name( "Raio da Morte" );
	Description( "    Atira um poderoso raio de  energia pura para desintegrar oalvo" );
	Name( "Escudo Energético" );
	Description( " Cria um escudo de energia que  absorve temporariamente parte        dos ataques recebidos   consumindo Mana" );
	Name( "Terremoto" );
	Description( " Cria um terremoto devastador,  atingindo todos os inimigos aoredor" );
	Name( "Espírito Elemental" );
	Description( "       Invoca um espírito para    aumentar o Poder de Ataque  temporariamente" );
	Name( "Espada Dançante" );
	Description( "Invoca uma espada mágica para  atacar os inimigos ao redor compoderes de fogo ou gelo" );
	Name( "Chama Elemental" );
	Description( "    Invoca o poderoso Chama       Elemental para ajudar nas   batalhas" );
	Name( "Onda de Fogo" );
	Description( "Cria uma onda de fogo gigante, atingindo todos os inimigos na área do ataque" );
	Name( "Distorção" );
	Description( "  Gera um pulso de energia que  reduz temporariamente o Poder   de Ataque e a Velocidade do   Ataque dos oponentes ao redor" );
	Name( "Meteoro" );
	Description( "Convoca uma chuva de meteoros  que caem do céu, atingindo todosos inimigos em volta" );
	Name( "T5_1_MGS" );
	Description( "T5_1_MGS" );
	Name( "T5_2_MGS" );
	Description( "T5_2_MGS" );
	Name( "T5_3_MGS" );
	Description( "T5_3_MGS" );
	Name( "T5_4_MGS" );
	Description( "T5_4_MGS" );
	Name( "T1_1_SS" );
	Description( "T1_1_SS" );
	Name( "T1_2_SS" );
	Description( "T1_2_SS" );
	Name( "T1_3_SS" );
	Description( "T1_3_SS" );
	Name( "T1_4_SS" );
	Description( "T1_4_SS" );
	Name( "T2_1_SS" );
	Description( "T2_1_SS" );
	Name( "T2_2_SS" );
	Description( "T2_2_SS" );
	Name( "T2_3_SS" );
	Description( "T2_3_SS" );
	Name( "T2_4_SS" );
	Description( "T2_4_SS" );
	Name( "T3_1_SS" );
	Description( "T3_1_SS" );
	Name( "T3_2_SS" );
	Description( "T3_2_SS" );
	Name( "T3_3_SS" );
	Description( "T3_3_SS" );
	Name( "T3_4_SS" );
	Description( "T3_4_SS" );
	Name( "T4_1_SS" );
	Description( "T4_1_SS" );
	Name( "T4_2_SS" );
	Description( "T4_2_SS" );
	Name( "T4_3_SS" );
	Description( "T4_3_SS" );
	Name( "T4_4_SS" );
	Description( "T4_4_SS" );
	Name( "T5_1_SS" );
	Description( "T5_1_SS" );
	Name( "T5_2_SS" );
	Description( "T5_2_SS" );
	Name( "T5_3_SS" );
	Description( "T5_3_SS" );
	Name( "T5_4_SS" );
	Description( "T5_4_SS" );
	Name( " - Força Orb" );
	Description( "          Aumenta o Ataque     temporariamente" );
	Name( "Desafio" );
	Description( "Mate os monstros indicados" );
	Name( "Desafio" );
	Description( "Mate os monstros indicados" );
	Name( "Desafio" );
	Description( "Mate os monstros indicados" );
	Name( "Desafio" );
	Description( "Mate os monstros indicados" );
	Name( "Absorção Extrema" );
	Description( "Aumenta a Absorção em 20 pontos" );
	Name( "Força Oculta" );
	Description( "Aumenta o Ataque em 15%" );
	Name( "Instinto de Sobrevivência" );
	Description( "Aumenta a Esquiva em 20%" );
};

void CTranslate::Translate( DWORD Offset, std::string Text )
{
	if( m_Address )
	{
		strcpy_s( ( char* )( m_Address + m_SpaceCount ), Text.length( ) + 1, Text.c_str( ) );
		WRITEMEMORY( Offset, ( m_Address + m_SpaceCount ) );
		m_SpaceCount += Text.length( ) + 1;
	};
}

CSkillTranslate::CSkillTranslate( )
{
	m_Address = ( DWORD )0x0098F668;
	m_SpaceCount = 0;
	m_VP = 0;
	SetTranslations( );
}

void CSkillTranslate::Name( std::string Name )
{
	if( m_Address )
	{
		DWORD Length = Name.length( ) + 1;
		if( Length > 64 ) Length = 64;
		VirtualProtect( ( LPVOID )( m_Address + m_SpaceCount ), Length, PAGE_EXECUTE_READWRITE, &m_VP );
		strcpy_s( ( char* )( m_Address + m_SpaceCount ), Length + 1, Name.c_str( ) );
		VirtualProtect( ( LPVOID )( m_Address + m_SpaceCount ), Length, PAGE_EXECUTE_READWRITE, &m_VP );
		m_SpaceCount += 64;
	};
}

void CSkillTranslate::Description( std::string Description )
{
	if( m_Address )
	{
		DWORD Length = Description.length( ) + 1;
		if( Length > 236 ) Length = 236;
		VirtualProtect( ( LPVOID )( m_Address + m_SpaceCount ), Length, PAGE_EXECUTE_READWRITE, &m_VP );
		strcpy_s( ( char* )( m_Address + m_SpaceCount ), Length + 1, Description.c_str( ) );
		VirtualProtect( ( LPVOID )( m_Address + m_SpaceCount ), Length, PAGE_EXECUTE_READWRITE, &m_VP );
		m_SpaceCount += 236;
	};
}